#
# Jenkins pipeline for CNaaS
#

disabled: false

slack:
  room: "cnaas-builds"

extra_jobs:
  - name: cnaas-front
    builders:
      - docker
    docker_name: cnaas/front
    docker_context_dir: docker/front

