#
# Jenkins pipeline for CNaaS Front
#

disabled: false

# slack:
#   room: "cnaas"

extra_jobs:
  - name: cnaas-front
    git:
      branch: develop    
    builders:
      - docker
    docker_name: cnaas/front
    docker_context_dir: .
    docker_tags:
      - "latest"

