apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cnaas-front
  name: cnaas-front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cnaas-front
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: cnaas-front
    spec:
      containers:
        - env:
            - name: CNAAS_API_URL
              value: https://api.cnaas-nms.{{ .Values.dns.prefix }}.surfwired.surf.net
            - name: CNAAS_AUTH_URL
              value: https://auth.cnaas-nms.{{ .Values.dns.prefix }}.surfwired.surf.net
            - name: CNAAS_FRONT_URL
              value: https://front.cnaas-nms.{{ .Values.dns.prefix }}.surfwired.surf.net
            - name: CNAAS_FIRMWARE_REPO_METADATA_URL
              value: https://cnaasfileserver.file.core.windows.net/cnaas-software/
            - name: CNAAS_FIRMWARE_REPO_URL
              value: https://cnaasfileserver.file.core.windows.net/cnaas-software/firmware/
          image: {{ .Values.front.image }}
          name: cnaas-front
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /opt/cnaas/cert
              name: cnaas-front-cert
      restartPolicy: Always
      volumes:
        - name: cnaas-front-cert
          persistentVolumeClaim:
            claimName: cnaas-front-cert
status: {}
